---
dependency:
  name: galaxy

driver:
  name: docker
  options:
    managed: true
    login_cmd_template: "docker exec -ti {instance} bash"

platforms:
  - name: test-base
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    command: ""

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."

verifier:
  name: ansible
