upstream active_app {
    server blue:80;
}
server {
    listen 80;

    location / {
        proxy_pass http://active_app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /health {
        return 200 'OK';
        add_header Content-Type text/plain;
    }
}
