# roles/wireguard/defaults/main.yml
---
wireguard_port: 51820
wireguard_server_ip: "10.0.0.1/24"
wireguard_interface: "wg0"
wireguard_network_interface: "ens4"   # GCP's default NIC name

wireguard_peers:
  - name: laptop
    public_key: "JC4/JbHwFlawmkNI7TD2hqEc1vxAvePAaIZhaZrHcQ8="
    allowed_ips: "10.0.0.2/32"
  # - name: phone
  #   public_key: "{{ lookup('file', '/etc/wireguard/phone_public.key') }}"
  #   allowed_ips: "10.0.0.3/32"
